add discovery operator sub
open-cluster-management/multiclusterhub-operator pull request #568
Opened 2021-04-30 19:00 UTC by cameronmwall

/hold

2021-05-03 12:41 UTC, zkayyali812 requested changes

2021-05-03 12:41 UTC, zkayyali812 commented on pkg/subscription/subscription_test.go
> +		{"Discovery subscription", Discovery(mch, ovr, "")},
Remove 3rd parameter to this function as Discovery should not need an ingress

2021-05-04 23:01 UTC, JakobGray commented on pkg/subscription/discovery.go
> +// Copyright (c) 2020 Red Hat, Inc.
```suggestion
// Copyright (c) 2021 Red Hat, Inc.
```

2021-05-05 17:48 UTC, nathanweatherly commented
/lgtm

2021-05-05 17:57 UTC, merged